version: 2.1

orbs:
 android: storytel/android@1.1.0

jobs:
 build:
   executor: android/android

   steps:
     - checkout
     - run:
         command: |
             sudo chmod +x ./gradlew
             sudo ./gradlew build
